# Generated by Django 4.2.4 on 2024-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=10, verbose_name='位置')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.BooleanField(default=False, verbose_name='灯光')),
                ('temperture', models.CharField(max_length=5, verbose_name='温度')),
                ('humidity', models.CharField(max_length=5, verbose_name='湿度')),
            ],
        ),
    ]
