# Generated by Django 4.2.4 on 2024-03-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_status_car_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='temperture',
            new_name='temperature',
        ),
    ]
