# Generated by Django 4.2.4 on 2024-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_temperture_status_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmd8266',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmd', models.CharField(max_length=200, verbose_name='指令')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='light',
        ),
        migrations.AddField(
            model_name='status',
            name='fire',
            field=models.BooleanField(default=False, verbose_name='火警'),
        ),
    ]
