# Generated by Django 4.2.4 on 2024-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_cmd8266_remove_status_light_status_fire'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='empty_self',
            field=models.IntegerField(default=0, verbose_name='空货位'),
        ),
    ]
